backend:
    name: git-gateway

editor:
    preview: false

media_folder: "src/static/img"
public_folder: "/static/img"

collections:
    - name: "links"
      label: "Links"
      folder: "src"
      create: true
      fields:
          - {
                label: "Layout",
                name: "layout",
                widget: "hidden",
                default: "base.njk"
            }
          - {
                label: "Name",
                name: "name",
                widget: "string",
                required: true,
                hint: "This is used in the admin menu, so that you can identify the link."
            }
          - {
                label: "Link",
                name: "title",
                widget: "string",
                required: true,
                pattern: ["^((?! ).)*$", "The link cannot contain spaces."],
                hint: "This is what appears after your site's url. This cannot contain spaces. Changes here will not take effect. If you want to change it then you have to delete this link and create a new one."
            }
          - {
                label: "Redirect",
                name: "link",
                widget: "string",
                required: true,
                pattern:
                    [
                        "^(http:|https:)(\/\/)(.+?(?=\\.))\\.(.+?(?=\/|$))",
                        "Invalid Redirect Link Make sure you have https:// included."
                    ],
                hint: "This is what users will be redirected to when they go to the link. Make sure to include https://"
            }
